import { Job } from './types';

const daysAgo = (days: number) => new Date(Date.now() - days * 86_400_000).toISOString();

const staticJobs: Omit<Job, 'recruiterId'>[] = [
  { id:'product-designer', title:'Senior Product Designer', company:'Orbit', initials:'O', accent:'#7c3aed', location:'Bengaluru, India', workMode:'Hybrid', jobType:'Full-time', experience:'Senior level', salary:'₹28L – ₹38L', postedAt:'2026-07-14', featured:true, skills:['Product design','Figma','Design systems'], summary:'Shape the tools that help teams make their most important decisions.', description:'Orbit is building a calmer, more capable workspace for high-performing teams. As a senior product designer, you will take complex workflows and turn them into clear, trustworthy experiences.', responsibilities:['Own end-to-end design for a product area, from discovery to polished delivery.','Partner closely with product and engineering to make sound trade-offs.','Raise the quality bar for our growing design system and team rituals.'], requirements:['5+ years designing digital products with a strong portfolio.','Comfortable with ambiguity, research, and systems thinking.','Exceptional craft in interaction and visual design.'] },
  { id:'frontend-engineer', title:'Frontend Engineer', company:'Pine Labs', initials:'P', accent:'#0f766e', location:'Remote, India', workMode:'Remote', jobType:'Full-time', experience:'Mid level', salary:'₹18L – ₹27L', postedAt:'2026-07-13', featured:true, skills:['React','TypeScript','Next.js'], summary:'Build reliable, fast financial experiences used by millions of people.', description:'Pine Labs is looking for a frontend engineer who cares deeply about performance and thoughtful interfaces. You will work on customer-facing surfaces that make commerce feel effortless.', responsibilities:['Build accessible React interfaces with a high bar for quality.','Collaborate with backend engineers on resilient product flows.','Improve platform performance, testing, and frontend foundations.'], requirements:['3+ years building production web applications.','Strong React, TypeScript, and CSS fundamentals.','Experience collaborating in a product-led team.'] },
  { id:'data-analyst', title:'Data Analyst', company:'Northstar', initials:'N', accent:'#b45309', location:'Mumbai, India', workMode:'Hybrid', jobType:'Full-time', experience:'Mid level', salary:'₹14L – ₹20L', postedAt:'2026-07-11', skills:['SQL','Python','Tableau'], summary:'Turn the signals behind product growth into clear decisions.', description:'Northstar helps independent businesses see where their growth comes from. You will make data understandable and useful for both customers and internal teams.', responsibilities:['Build recurring analysis and self-serve reporting.','Partner with product to define meaningful success metrics.','Translate ambiguous questions into clear, rigorous analysis.'], requirements:['2+ years in analytics or business intelligence.','Advanced SQL and comfort working with large datasets.','Clear communication for technical and non-technical audiences.'] },
  { id:'backend-engineer', title:'Backend Engineer', company:'Fieldnote', initials:'F', accent:'#be123c', location:'Pune, India', workMode:'On-site', jobType:'Full-time', experience:'Senior level', salary:'₹24L – ₹34L', postedAt:'2026-07-09', skills:['Node.js','PostgreSQL','AWS'], summary:'Design the dependable systems behind a new generation of field work.', description:'Fieldnote gives field teams the clarity to do great work. We are seeking an engineer who enjoys designing pragmatic services and making systems easier to operate.', responsibilities:['Design and operate APIs and asynchronous workflows.','Improve observability, reliability, and developer experience.','Mentor teammates through thoughtful reviews and pairing.'], requirements:['5+ years backend engineering experience.','Strong Node.js and relational data modeling experience.','A practical approach to distributed systems and operations.'] },
  { id:'content-strategist', title:'Content Strategist', company:'Juniper', initials:'J', accent:'#0369a1', location:'Delhi, India', workMode:'Remote', jobType:'Contract', experience:'Mid level', salary:'₹10L – ₹15L', postedAt:'2026-07-07', skills:['Content strategy','SEO','B2B SaaS'], summary:'Give a distinct, useful voice to a platform built for modern operations.', description:'Juniper makes operational software that feels remarkably simple. You will define our editorial point of view and create content that makes a complex category approachable.', responsibilities:['Plan and deliver a high-quality editorial calendar.','Turn customer insight into useful, well-researched stories.','Work with design and growth on distribution experiments.'], requirements:['4+ years in content strategy or editorial roles.','Strong B2B product storytelling samples.','A sharp editorial eye and organised working style.'] },
  { id:'customer-success', title:'Customer Success Manager', company:'Tandem', initials:'T', accent:'#4f46e5', location:'Gurugram, India', workMode:'Hybrid', jobType:'Full-time', experience:'Entry level', salary:'₹8L – ₹12L', postedAt:'2026-07-05', skills:['Account management','SaaS','Onboarding'], summary:'Help ambitious teams get lasting value from the way they work together.', description:'Tandem supports modern teams with a collaborative work platform. You will guide customers from first launch through long-term success and advocacy.', responsibilities:['Lead onboarding and strategic check-ins for customers.','Spot risks early and coordinate the right internal support.','Share customer patterns to influence product decisions.'], requirements:['1+ years in customer-facing SaaS, consulting, or operations.','Empathy, curiosity, and excellent written communication.','Comfortable managing multiple priorities with care.'] }
];

export const jobs: Job[] = staticJobs.map((job, index) => ({
  ...job,
  recruiterId: `seed-recruiter-${index + 1}`,
  postedAt: daysAgo(index === 0 ? 1 : index * 2),
}));

export const getJob = (id: string) => jobs.find((job) => job.id === id);
